config/routes.rb

Rails.application.routes.draw do
  resources :replies
    root 'static_pages#home'
    get 'static_pages/home'
    resources :reviews
    resources :companies
    # root 'admin#index'
    resources :users
    get 'admin/index'
    get 'sessions/new'
    get 'sessions/create'
    get 'sessions/destroy'
        
    controller :sessions do
        get 'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
      validates :name, presence: true
    has_many :review, -> { order "created_at ASC"}
    has_one_attached :image
    has_many :user
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    @companies = if params[:term]
        Company.where('name LIKE ?', "%#{params[:term]}%")
    else
        Company.all
    end
  end

  # GET /companies/1 or /companies/1.json
  def show
    @review = Review.new
    @reply = Reply.new
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :programming_langue, :vacancy, :location, :website_link, :description, :detail_desc, :image, :term)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
    <% if company.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>
            <ul>
                <% company.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="mb-3">
        <%= form.label :name , :class => "form-label" %>
        <%= form.text_field :name , :class => "form-control" %>
    </div>
    <div class="mb-3">
        <%= form.label :programming_langue , :class => "form-label" %>
        <%= form.text_field :programming_langue , :class => "form-control" %>
    </div>
    <div class="mb-3">
        <%= form.label :vacancy , :class => "form-label" %>
        <%= form.text_field :vacancy , :class => "form-control "%>
    </div>
    <div class="mb-3">
        <%= form.label :location , :class => "form-label" %>
        <%= form.text_field :location , :class => "form-control" %>
    </div>
    <div class="mb-3">
        <%= form.label :website_link, :class => "form-label" %>
        <%= form.text_field :website_link , :class => "form-control" %>
    </div>
    <div class="mb-3">
        <%= form.label :description , :class => "form-label"%>
        <%= form.text_field :description , :class => "form-control" %>
    </div>
    <div class="mb-3">
        <%= form.label :detail_desc, :class => "form-label" %>
        <%= form.text_area :detail_desc , :class => "tinymce", :rows => 40, :cols => 120 %>
    </div>
    <div class="mb-3">
        <%= form.label :image , :class => "form-label" %>
        <%= form.file_field :image , :class => "form-label" %><br>
    </div>
    <div class="actions text-center">
        <%= form.submit "作成" , class: 'btn btn-danger px-5' %>
    </div>
<% end %>

app/views/companies/edit.html.erb
<div class="text-center">
    <h1>会社情報の修正</h1>
</div>
<%= render 'form', company: @company %>
<%= link_to 'Show', @company , class: 'btn btn-outline-danger'  %> 
<%= link_to 'Back', companies_path , class: 'btn btn-outline-danger' %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>
<div class="content">
    <h1 class="text-center m-2">会社一覧</h1>
    <% if logged_in?  && current_user.role == "admin" %>
        <%= link_to '会社情報作成', new_company_path , :class => "btn btn-danger" %>
    <% end %>
    <div class="container">
        <% @companies.each do |company| %>
            <div class="row company-item theme-box">
                <div class="col-4 logo-container">
                    <a href="/companies/<%= company.id %>">
                        <% if company.image.attached? %>
                            <%= image_tag company.image , :class => "img-thumbnail"%>
                        <% else%>
                            <img src="/images/logo/logo-default.jpeg" class="img-thumbnail" alt="...">
                        <% end %>
                    </a>
                </div>
                <div class="col-10">
                    <h2 class="company-name m-2">
                        <a href="/companies/<%= company.id %>"><%= company.name %></a>
                    </h2>
                    <div class="language m-2">
                        <i class="bi bi-gear-fill"></i>
                        <span><%= company.programming_langue %></span>
                    </div>
                    <div class="description m-2">
                        <i class="bi bi-person-square"></i>
                        <span><%= company.description %></span>
                    </div>
                    <div class="location m-2">
                        <i class="bi bi-geo-alt-fill"></i>
                        <span><%= company.location %></span>
                    </div>
                    <div class="website m-2">
                        <i class="bi bi-globe"></i>
                        <span><a href="<%= company.website_link %>" target="_blank"><%= company.website_link %></a></span>
                    </div>
                    <% if logged_in?  && current_user.role == "admin" %>
                        <div class="m-2" style="text-align: right;">
                            <%= link_to '修正', edit_company_path(company) , :class => "btn btn-outline-danger mx-3" %>
                            <%= link_to '削除', company, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger" %>
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/companies/new.html.erb
<div class="text-center">
    <h1>会社情報作成</h1>
</div>
<%= render 'form', company: @company %>
<%= link_to 'Back', companies_path , class: 'btn btn-outline-danger' %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<div id="company-detail">
    <div id="company-detail-info container">
        <div class="row company-item ">
            <div class="col-4 logo-container">
                <a href="/companies/<%= @company.id %>">
                    <% if @company.image.attached? %>
                        <%= image_tag @company.image , :class => "img-thumbnail"%>
                    <% else%>
                        <img src="/images/logo/logo-default.jpeg" class="img-thumbnail" alt="...">
                    <% end %>
                </a>
            </div>
            <div class="col-8">
                <h2 class="company-name m-2">
                    <a href="/companies/<%= @company.id %>"><%= @company.name %></a>
                </h2>
                <div class="language m-2">
                    <i class="bi bi-gear-fill"></i>
                    <span><%= @company.programming_langue %></span>
                </div>
                <div class="description m-2">
                    <i class="bi bi-person-square"></i>
                    <span><%= @company.description %></span>
                </div>
                <div class="location m-2">
                    <i class="bi bi-geo-alt-fill"></i>
                    <span><%= @company.location %></span>
                </div>
                <div class="website m-2">
                    <i class="bi bi-globe"></i>
                    <span><a href="<%= @company.website_link %>" target="_blank"><%= @company.website_link %></a></span>
                </div>
            </div>
        </div>
    </div>
    <div id="company-detail-desc" class="container theme-box">
        <div class="row">
            <h4>会社情報</h4>
            <div id="company-detail-desc-content">
                <%= sanitize @company.detail_desc %>
            </div>
        </div>
    </div>
</div>
<div id="review-company" class="theme-box">
    <% if !logged_in? %>
        <div class="my-2">
            <i class="bi bi-exclamation-square-fill text-danger"></i>
            <span class="mx-2">コメントする時はログインしている必要があります。</span>
        </div>
    <% end %>
    <%= form_with(model: @review, local: true) do |form| %>
        <div class="mb-3">
            <%= form.text_area :review , :class => "form-control"%>
        </div>
        <div class= "field">
            <%= form.hidden_field :company_id, :value => @company.id %>
        </div>
        <div class="actions text-center">
            <input type="submit" name="commit" value="コメント" class="btn btn-danger fw-bold" data-disable-with="コメント" <%= logged_in? ? '' : "disabled" %>>
        </div>
    <% end %>
</div>
<div id="comment-list">
    <h3 class="text-center m-2">コメント一覧</h3>
    <div class="container">
        <% @company.review.each do |review|%>
            <div class="row company-item theme-box">
                <div class="col">
                    <div class="comment-list-detail">
                        <div class="comment-list-header row">
                            <div class="col-8">
                                <i class="bi bi-person-circle"></i>
                                <span> <%= review.user.name %> </span>
                            </div>
                            <div class="col-4" style="text-align: right;">
                                <i class="bi bi-clock-fill"></i>
                                <span> <%= review.created_at %> </span>
                            </div>
                        </div>
                        <div class="comment-list-content">
                            <p> <%= review.review %></p>
                        </div>
                        <div class="reply-symbol">
                            <button class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#modal-reply<%= review.id %>" <%= logged_in? ? '' : "disabled" %> ><i class="bi bi-reply-fill"></i></button>
                        </div>
                        <div class="modal fade" id="modal-reply<%= review.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Reply</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <%= form_with(model: @reply, local: true) do |form| %>
                                        <div class="modal-body">
                                            <div class="field">
                                                <%= form.hidden_field :review_id, :value => review.id %>
                                                <%= form.hidden_field :company_id , :value => @company.id %>
                                            </div>
                                            <div class="field">
                                                <%= form.text_area :content , :class => "form-control"%>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <%= form.submit "Save change" , class: 'btn btn-outline-danger' %>
                                        </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="reply-list">
                        <% review.reply.each do |reply|%>
                            <div class="reply-item">
                                <p> <strong> <%= reply.user.name %></strong> - <%= reply.created_at %> </p>
                                <p> <%= reply.content %> </p>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
<div class="my-5" style="text-align: right;">
    <%= link_to 'Back', companies_path , class: 'btn btn-outline-danger' %>
</div>