config/routes.rb

Rails.application.routes.draw do
  resources :replies
    root 'static_pages#home'
    get 'static_pages/home'
    resources :reviews
    resources :companies
    # root 'admin#index'
    resources :users
    get 'admin/index'
    get 'sessions/new'
    get 'sessions/create'
    get 'sessions/destroy'
        
    controller :sessions do
        get 'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Project</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <script src="https://cdn.tiny.cloud/1/up47n387bsvwk9o4t2c5am3dzhbh9nlmxkwfz50ldckxn3mm/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
        <script>
            tinymce.init({
              selector: '.tinymce',
              height: 500,
              menubar: true,
              plugins: [
                'advlist autolink lists link image charmap print preview anchor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table paste code help wordcount'
              ],
                toolbar: 'undo redo | formatselect | ' +
                ' bold italic backcolor | alignleft aligncenter ' +
                ' alignright alignjustify | bullist numlist outdent indent | ' +
                ' removeformat | help'
            });
        </script>
        <div class="header mb-3">
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <div class="header-logo">
                        <a href="/">
                            <img src="https://jobufea.com/static/media/logo.4ab951a2.jpg">
                        </a>
                    </div>
                    <%= link_to "ホーム", root_path , class: "navbar-brand menu-item"%>
                    <%= link_to "会社", companies_path , class: "navbar-brand menu-item"%>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item menu-item">
                                <% if logged_in? %>
                                    <%= link_to current_user.name, users_path , class: "nav-link" %>
                                <% else %>
                                    <%= link_to "ログイン", login_url , class: "nav-link" %>
                                <% end %>
                            </li>
                            <li class="nav-item menu-item">
                                <% if !logged_in? %>
                                    <%= link_to "登録", new_user_path,class: "nav-link" %>
                                <% end %>
                            </li>
                            <li class="nav-item menu-item">
                                <% if logged_in?  && current_user.role == "admin" %>
                                    <%= link_to "settings", admin_index_path,class: "nav-link" %>
                                <% end %>
                            </li>
                        </ul>
                        <%= form_tag(companies_path, method: :get , class: "d-flex") do %>
                            <%= text_field_tag :term , nil ,class: "form-control mx-2" ,placeholder: "会社名で会社情報を検索" %>
                            <button class="btn" type="submit" style="background-color: #fff;"><i class="bi bi-search"></i></button>
                        <% end %>
                    </div>
                </div>
            </nav>
        </div>
        <div class="container">
            <%= yield %>
        </div>
    </body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</html>